const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../docs/index.html'),'utf8');
function fn(name){const start=source.indexOf('function '+name+'(');return source.slice(start,source.indexOf('\n}',start)+2);}
function quote(prop,line){const ctx={ODDS:{props:{hits:{player:{line,over:2,under:2}},hrr:{player:{line,over:2,under:2}},pk:{player:{line,over:2,under:2}}}},oddsMatchSlate:()=>true,normName:()=> 'player',decimalToAmerican:x=>100*(x-1)};vm.createContext(ctx);vm.runInContext(fn('propPriceDecimal')+'\n'+fn('fetchedPropFor'),ctx);return ctx.fetchedPropFor(prop,'Player');}
test('Hit and combined hit/run/RBI probabilities require their exact supported lines',()=>{for(const prop of ['hit','hits']){assert.ok(quote(prop,.5));for(const line of [1.5,2.5,0,null,'',NaN])assert.equal(quote(prop,line),null);}assert.ok(quote('hrr',1.5));assert.equal(quote('hrr',.5),null);assert.equal(quote('hrr',2.5),null);});
test('Strikeout quotes retain real half-point thresholds and reject refund contracts',()=>{assert.ok(quote('pk',6.5));assert.ok(quote('k','4.5'));for(const line of [6,0,-1,Infinity,null])assert.equal(quote('pk',line),null);});
test('Cross-game ideas exclude repeated and unidentified games',()=>{const ctx={sgpTypes:new Set(['HR']),sgpMode:'likelihood',sgpLegs:3,sgpSameGame:false};vm.createContext(ctx);vm.runInContext(fn('genParlay'),ctx);const pool=[{name:'A',game_pk:1,prob:.8},{name:'B',game_pk:'1',prob:.7},{name:'C',game_pk:2,prob:.6},{name:'D',game_pk:null,prob:.9}].map(x=>({...x,tk:'HR'}));assert.equal(ctx.genParlay(pool).map(x=>x.name).join(','),'A,C');});
test('Same-game research never displays multiplied ticket odds or a combined chance',()=>{const main={innerHTML:''},legs=[{name:'A',tk:'HR',label:'Over 0.5 HR',prob:.4,price:200,team:'A',opp:'B'},{name:'B',tk:'HR',label:'Over 0.5 HR',prob:.5,price:150,team:'B',opp:'A'}];const ctx={document:{getElementById:()=>main},BOARD:{players:[]},genParlay:()=>legs,sgpPool:()=>[],sgpTypes:new Set(['HR']),sgpLegs:2,sgpMode:'likelihood',sgpSameGame:true,chipColor:()=>'',fmtAm:String};vm.createContext(ctx);vm.runInContext(fn('renderSGP'),ctx);ctx.renderSGP();assert.match(main.innerHTML,/Not estimated/);assert.match(main.innerHTML,/Not supplied/);assert.doesNotMatch(main.innerHTML,/20\.0%|\$10 pays/);ctx.sgpSameGame=false;ctx.renderSGP();assert.match(main.innerHTML,/20\.0%/);assert.match(main.innerHTML,/assumes the games behave independently/);});
test('An Under recommendation keeps its actual side probability and label in the builder',()=>{const ctx={BOARD:{players:[{name:'A',id:1,heat:80}],pitcher_props:[]},allPropEV:()=>[{name:'A',propLabel:'1+ Hits',side:'under',line:.5,price:180,ev:.12,prob:.4}],calibratedHRprob:()=>null,badgeAwarePropProb:t=>t==='hit1'?.6:null,americanFair:()=>100,americanToDecimal:x=>1+x/100};vm.createContext(ctx);vm.runInContext(fn('_sgpType')+'\n'+fn('sgpPool'),ctx);const leg=ctx.sgpPool()[0];assert.equal(leg.prob,.4);assert.equal(leg.label,'Under 0.5 Hit');assert.equal(leg.price,180);});
